Statistics/urls.py
from django.urls import path
from .views import *

app_name = 'statistics'
urlpatterns = [
    path('', statistics_view, name='statistics_view'),

    path('get-latest-data/', get_latest_data, name='get_latest_data'),

    path('export_excel_workers/',  export_excel_workers,  name='export_excel_workers'),

    path('export_excel_values/',  export_excel_values,  name='export_excel_values'),

    path('export_excel_time/',  export_excel_time,  name='export_excel_time'),
]

index/urls.py
from django.urls import path


from .views import *

app_name = 'index'
urlpatterns = [
    path('', index_view, name='index_view'),

]

login/urls.py
from django.urls import path

from user.views import user_details
from .views import *

app_name = 'login'
urlpatterns = [
    path('', login, name='login_view'),

    path('enroll/', enroll, name='enroll'),

    path('user_details/', user_details, name='user_details'),

    path('logout/', logout, name='logout'),

    path('code/', image_code, name="image_code"),

    path('retrieve/', retrieve_view, name="retrieve_view"),

    path('', retrieve_return, name="retrieve_return"),
]

search/urls.py
from django.urls import path
from .views import *

app_name = 'search'
urlpatterns = [
    path('<int:page>/', search_view, name='search_view'),

    path('', default_view, name='default_view')
]

user/urls.py
from django.urls import path
from .views import *

app_name = 'user'
urlpatterns = [
    path('<int:page>/', user_view, name='user_view'),

    path('<int:page>/<int:id>/', work_time_, name='work_time_'),

    path('workers/', workers, name='workers'),

    path('user_modify/', user_modify, name='user_modify'),
]

video/urls.py
from django.urls import path
from .views import *

app_name = 'video'
urlpatterns = [
    path('', video_feed, name='video_feed'),
]

Statistics/models.py
from django.db import models


class value(models.Model):
    tem = models.FloatField(verbose_name="温度")
    humidity = models.FloatField(verbose_name="湿度")
    time = models.DateTimeField(verbose_name="时间")

login/models.py
from django import forms
from django.db import models


class user_login(models.Model):
    username = models.CharField(verbose_name="用户名",  max_length=64)
    password = models.CharField(verbose_name="密码",  max_length=64)
    name = models.CharField(verbose_name="姓名",  max_length=64)
    phone = models.CharField(verbose_name="电话",  max_length=64)
    email = models.CharField(verbose_name="邮箱",  max_length=20)

search/models.py
from django.db import models

# Create your models here.

user/models.py
from django.db import models


class UserInfo(models.Model):
    name = models.CharField(verbose_name="姓名", max_length=64)
    age = models.IntegerField(verbose_name="年龄")
    salary = models.DecimalField(verbose_name="收入", max_digits=10, decimal_places=2, default=0)
    tel = models.CharField(verbose_name="电话", max_length=32)
    create_time = models.DateField(verbose_name="入职时间")
    gender_choice = (
        (0, "男"),
        (1, "女")
    )
    gender = models.SmallIntegerField(verbose_name="性别", choices=gender_choice)
    email = models.CharField(verbose_name="邮箱", max_length=20)

    def __str__(self):
        return self.name


class work_time(models.Model):
    username = models.ForeignKey(verbose_name="值班人员", to=UserInfo, on_delete=models.CASCADE)
    time = models.DateField(verbose_name="值班时间", max_length=64)

    def __str__(self):
        return self.time

Statistics/views.py
import time

from django.core.serializers import serialize
from django.shortcuts import render
from django.utils import timezone

from Statistics.models import value
from django.http import JsonResponse
from Statistics.management.commands.runapscheduler import my_job
from user import models as user_models
from Statistics import models as Statistics_models
import xlsxwriter
from django.http import HttpResponse
from datetime import datetime


def statistics_view(request):
    queryset1 = value.objects.order_by('-id')[:120].values('tem')
    queryset2 = value.objects.order_by('-id')[:120].values('humidity')
    list_data1 = []
    list_data2 = []
    list1 = list(queryset1)
    list2 = list(queryset2)
    for i in range(60):
        data1 = list1[59 - i]['tem']
        data2 = list2[59 - i]['humidity']
        list_data1.append(data1)
        list_data2.append(data2)
    return render(request, 'statistics.html', {
        'list_data1': list_data1,
        'list_data2': list_data2,
    })


def get_latest_data(request):
    now = timezone.now()

    seconds = now.second
    milliseconds = now.microsecond // 1000

    if milliseconds <= 250:
        rounded_seconds = 0
    else:
        rounded_seconds = 5

    if seconds != rounded_seconds:
        now = now.replace(second=rounded_seconds, microsecond=0)

    #  Format  the  datetime  object  to  the  desired  string  format
    formatted_now = now.strftime('%Y-%m-%d    %H:%M:%S') + '.000000'

    print(formatted_now)
    try:
        #  假设  'time'  是存储时间的字段名称
        last_data = value.objects.filter(time=formatted_now).first()
        data = {
            'tem': last_data.tem,
            'humidity': last_data.humidity,
        }
        return JsonResponse(data)
    except:
        data = {
            'tem': 22.1,
            'humidity': 51.1,
        }
        #  如果没有找到数据，可以返回一个错误或者空的数据
        return JsonResponse(data)


def export_excel_workers(request):
    now = datetime.now().replace(second=0, microsecond=0)
    # 准备要写入 Excel 表格的数据
    data = user_models.UserInfo.objects.all()
    for value_ in data:
        for field in user_models.UserInfo._meta.fields:  # _meta.fields包含模型的所有字段信息
            print(f"{field.name}:  {getattr(value_, field.name)}")
        print("\n")
    #  创建一个空列表来保存字段名
    fields = [field.name for field in user_models.UserInfo._meta.fields]
    # 创建一个 HttpResponse 对象，用来输出 Excel 文件
    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = f'attachment; filename="User_Info--{now}.xlsx"'

    writer = xlsxwriter.Workbook(response, {'in_memory': True})
    worksheet = writer.add_worksheet('Sheet1')
    #  写入字段名
    for col, field_name in enumerate(fields):
        worksheet.write(0, col, field_name)
    row_num = 1
    for row_data in data:
        col_num = 0  # 初始化列号
        for field_name in fields:
            #  使用  getattr  获取模型实例的字段值
            col_data = getattr(row_data, field_name)
            if field_name == 'time':
                col_data = col_data.strftime("%Y-%m-%d %H:%M:%S")
            #  将字段值写入当前行和列
            worksheet.write(row_num, col_num, col_data)
            col_num += 1  # 移动到下一列
        row_num += 1  # 移动到下一行
    # 关闭 writer 对象，提交响应
    writer.close()
    return response


def export_excel_values(request):
    now = datetime.now().replace(second=0, microsecond=0)
    # 准备要写入 Excel 表格的数据
    data = Statistics_models.value.objects.all()
    for value_ in data:
        for field in Statistics_models.value._meta.fields:  # _meta.fields包含模型的所有字段信息
            print(f"{field.name}:  {getattr(value_, field.name)}")
        print("\n")
    #  创建一个空列表来保存字段名
    fields = [field.name for field in Statistics_models.value._meta.fields]
    # 创建一个 HttpResponse 对象，用来输出 Excel 文件
    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = f'attachment; filename="values--{now}.xlsx"'

    writer = xlsxwriter.Workbook(response, {'in_memory': True})
    worksheet = writer.add_worksheet('Sheet2')
    #  写入字段名
    for col, field_name in enumerate(fields):
        worksheet.write(0, col, field_name)
    row_num = 1
    for row_data in data:
        col_num = 0  # 初始化列号
        for field_name in fields:
            #  使用  getattr  获取模型实例的字段值
            col_data = getattr(row_data, field_name)
            if field_name == 'time':
                col_data = col_data.strftime("%Y-%m-%d %H:%M:%S")
            #  将字段值写入当前行和列
            worksheet.write(row_num, col_num, col_data)
            col_num += 1  # 移动到下一列
        row_num += 1  # 移动到下一行
    # 关闭 writer 对象，提交响应
    writer.close()
    return response


def export_excel_time(request):
    now = datetime.now().date()
    # 准备要写入 Excel 表格的数据
    data = user_models.work_time.objects.filter(time=now)

    for value_ in data:
        for field in user_models.work_time._meta.fields:  # _meta.fields包含模型的所有字段信息
            print(f"{field.name}:  {getattr(value_, field.name)}")
        print("\n")
    #  创建一个空列表来保存字段名
    fields = [field.name for field in user_models.work_time._meta.fields]
    # 创建一个 HttpResponse 对象，用来输出 Excel 文件
    response = HttpResponse(content_type='application/ms-excel')
    response['Content-Disposition'] = f'attachment; filename="workers--{now}.xlsx"'

    writer = xlsxwriter.Workbook(response, {'in_memory': True})
    worksheet = writer.add_worksheet('Sheet3')
    #  写入字段名
    for col, field_name in enumerate(fields):
        worksheet.write(0, col, field_name)
    row_num = 1
    for row_data in data:
        col_num = 0  # 初始化列号
        for field_name in fields:
            #  使用  getattr  获取模型实例的字段值
            col_data = getattr(row_data, field_name)
            if type(col_data) != str:
                col_data = str(col_data)
            #  将字段值写入当前行和列
            worksheet.write(row_num, col_num, col_data)
            col_num += 1  # 移动到下一列
        row_num += 1  # 移动到下一行
    # 关闭 writer 对象，提交响应
    writer.close()
    return response

search/views.py
from django.shortcuts import render
from django.db.models import Q
from django.core.paginator import Paginator
from user.models import *


def search_view(request, page):
    word = request.GET.get('word_', '')  # 获取关键字
    if word:
        workers = UserInfo.objects.filter(Q(name__icontains=word) | Q(tel__icontains=word))
    else:
        workers = UserInfo.objects.all()
    return render(request, 'search.html', {
        'workers': workers,
        'word': word
    })


def default_view(request):
    return search_view(request, 1)

video/views.py
import cv2
from django.http import StreamingHttpResponse


#  将生成器函数定义在视图函数外部
def video_frame_generator(ip, user, password):
    cap = cv2.VideoCapture("rtsp://" + user + ":" + password + "@" + ip + ":554/h264/ch1/main/av_stream")
    try:
        while True:
            ret, frame = cap.read()
            if not ret:
                break
            (flag, encodedImage) = cv2.imencode(".jpg", frame)
            if not flag:
                continue
            yield (b'--frame\r\n'
                   b'Content-Type:  image/jpeg\r\n\r\n' + bytearray(encodedImage) + b'\r\n')
    finally:
        cap.release()


def video_feed(request):
    #  摄像头配置
    ip = '192.168.1.64'
    user = 'admin'
    password = 'yu20021014..'

    #  返回流响应
    return StreamingHttpResponse(video_frame_generator(ip, user, password),
                                 content_type="multipart/x-mixed-replace;boundary=frame")

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>distribution_room</title>
    <link href="{% static 'css/layui.css' %}" rel="stylesheet">
    <link rel="shortcut icon" href="{% static 'img/enroll/favicon.ico' %}">
    {% block link %}
    {% endblock %}
</head>
{% block style %}
{% endblock %}
<style>
    .person {
        float: right;
    }
</style>

<body style="background:url({% static 'img/statistics/bg_body.jpg' %})">
<ul class="layui-nav layui-bg-black">
    <li class="layui-nav-item"><a href="/user/1/">员工列表</a></li>
    <li class="layui-nav-item"><a href="/user/workers/">值班人员</a></li>
    <li class="layui-nav-item"><a href="/statistics">数据统计</a></li>
    <li class="layui-nav-item"><a href="/video">监控画面</a></li>
    <li class="layui-nav-item person" style="margin-right: 30px">
        <a href="#" style="pointer-events: none">
            {% if request.session.info.user %}
                {{ request.session.info.user  }}
            {% endif %}
        </a>
        <dl class="layui-nav-child">
            <dd><a href="{% url 'login:user_details' %}">我的信息</a></dd>
            <dd><a href="{% url 'user:user_modify' %}">修改密码</a></dd>
            <dd><a href="{% url 'index:index_view' %}">退出账号</a></dd>
        </dl>
    </li>
</ul>


<div class="layui-form-item search">
    <form method="get" action="{% url 'search:search_view' 1 %}">
        <div class="layui-input-group" style="margin:5px auto 0;">
            <label>
                <input type="text" placeholder="搜索指定员工" value="{{ word }}" class="layui-input" name="word_">
            </label>
            <input class="layui-btn layui-bg-blue" type="submit" value="搜索">
        </div>
    </form>
</div>

{% block body %}
{% endblock %}


<script src="{% static 'js/layui.js' %}"></script>
{% block js %}
{% endblock %}
</body>
</html>

templates/enroll.html
<!DOCTYPE html>
<html lang="en"><!-- Basic -->
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>登录</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="{% static 'img/enroll/favicon.ico' %}" type="image/x-icon">
    <link href="{% static 'css/enroll/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/enroll/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/enroll/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/enroll/responsive.css' %}">
    <link rel="stylesheet" href="{% static 'css/layui.css' %}">
</head>


<body>
<div id="particles-js" class="main-form-box">
    <div class="md-form">
        <div class="container">
            <div class="row">
                <div class="col-md-6 offset-md-3">
                    <div class="panel panel-login">
                        <div class="logo-top">
                            <a href="#"><img src="{% static 'img/enroll/logo.png' %}" alt=""/></a>
                        </div>
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-lg-12">
                                    <form id="enroll-form" action="{% url  'login:enroll' %}" method="post" role="form"
                                          style="display:  block;" onsubmit="return  handleFormSubmit(event);">
                                        {% csrf_token %}
                                        <div class="form-group">
                                            <label class="icon-lp" style="margin: 6px 0 0 7px">
                                                <i class="layui-icon layui-icon-username"></i>
                                            </label>
                                            <input type="text" name="username" id="username" tabindex="1"
                                                   class="form-control" placeholder="用户名" value="" required=""
                                                   autoComplete="off">
                                            <span style="color: red">{{ form.username.errors.0 }}</span>
                                        </div>


                                        <div class="form-group">
                                            <label class="icon-lp" style="margin: 6px 0 0 7px">
                                                <i class="layui-icon layui-icon-password"></i>
                                            </label>
                                            <input type="password" name="password" id="Password" tabindex="2"
                                                   class="form-control" placeholder="密码" required="">
                                            <span style="color: red">{{ form.password.errors.0 }}</span>
                                        </div>

                                        <div class="form-group">
                                            <label class="icon-lp" style="margin: 6px 0 0 7px">
                                                <i class="layui-icon layui-icon-friends"></i>
                                            </label>
                                            <input type="text" name="name" id="name" tabindex="2"
                                                   class="form-control" placeholder="姓名" required="">
                                        </div>

                                        <div class="form-group">
                                            <label class="icon-lp" style="margin: 6px 0 0 7px">
                                                <i class="layui-icon layui-icon-cellphone"></i>
                                            </label>
                                            <input type="text" name="phone" id="phone" tabindex="2"
                                                   class="form-control" placeholder="电话" required
                                                   pattern="^1\d{10}$">
                                        </div>


                                        <div class="form-group">
                                            <label class="icon-lp" style="margin: 6px 0 0 7px">
                                                <i class="layui-icon layui-icon-cellphone"></i>
                                            </label>
                                            <input type="text" name="email" id="email" tabindex="2"
                                                   class="form-control" placeholder="邮箱" required
                                                   pattern="^[a-zA-Z0-9_.-]+@[a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+)*\.[a-zA-Z0-9]{2,6}$">
                                        </div>

                                        <div class="form-group">
                                            <div class="row">
                                                <div class="col-sm-7">
                                                    <label class="icon-lp" style="margin: 6px 0 0 7px">
                                                        <i class="layui-icon layui-icon-vercode"
                                                           style="margin: 6px 0 0 7px"></i>
                                                    </label>
                                                    <input type="text" name="Captcha" id="Captcha" tabindex="2"
                                                           class="form-control" placeholder="请输入验证码">
                                                    <span style="color: red">{{ error_message }}</span>
                                                </div>
                                                <div class="col-sm-5">
                                                    <div style="margin: 10px 0 0 30px;">
                                                        <img src="/login/code/" alt="" id="captchaImg">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>


                                        <div class="form-group">
                                            <div class="row">
                                                <!--    登录按钮    -->
                                                <div class="col-sm-6">
                                                    <a class="form-control  btn  btn-login"
                                                       style="height:  100%;  color:  white"
                                                       href="{% url  "login:login_view" %}">登录</a>
                                                </div>

                                                <!--    注册按钮    -->
                                                <div class="col-sm-6">
                                                    <input type="submit" name="enroll-submit" id="enroll-submit"
                                                           tabindex="4" class="form-control  btn  btn-login"
                                                           value="注册">
                                                </div>
                                            </div>
                                        </div>
                                    </form>

                                    <a href="#" style="float: right; color: red">忘记密码?</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<script src="{% static 'js/enroll/jquery.min.js' %}"></script>
<script src="{% static 'js/enroll/bootstrap.min.js' %}"></script>
<script src="{% static 'js/enroll/particles.min.js' %}"></script>
<script src="{% static 'js/enroll/index.js' %}"></script>
<script type="text/javascript">
    $(function () {
        $('#login-form-link').click(function (e) {
            $("#login-form").delay(100).fadeIn(100);
            $("#register-form").fadeOut(100);
            $('#register-form-link').removeClass('active');
            $(this).addClass('active');
            e.preventDefault();
        });
        $('#register-form-link').click(function (e) {
            $("#register-form").delay(100).fadeIn(100);
            $("#login-form").fadeOut(100);
            $('#login-form-link').removeClass('active');
            $(this).addClass('active');
            e.preventDefault();
        });
    })

    document.getElementById('captchaImg').addEventListener('click', function () {
        //  调用后端视图函数以获取新的captcha图像
        fetch('/login/code/')
            .then(response => response.blob())
            .then(blob => {
                //  更新图像的src属性以显示新的captcha
                document.getElementById('captchaImg').src = URL.createObjectURL(blob);
            });
    });
</script>

</body>
</html>

templates/error.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>错误</title>
    <link rel="shortcut icon" href="{% static 'img/enroll/favicon.ico' %}">
</head>
<body style="background:url({% static 'img/statistics/bg_body.jpg' %})">
<div style="color: red;text-align: center;font-size: 50px;margin-top: 14%">用户名或密码未填写完整，请返回重新修改!!!</div>

<div style="color: white;text-align: center;font-size: 50px;margin-top: 14%"><a href="{% url 'user:user_modify' %}" style="text-decoration: none">返回</a></div>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en"><!-- Basic -->
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>登录</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="{% static 'img/enroll/favicon.ico' %}" type="image/x-icon">
    <link href="{% static 'css/enroll/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/enroll/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/enroll/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/enroll/responsive.css' %}">
    <link rel="stylesheet" href="{% static 'css/layui.css' %}">
</head>


<body>
<div id="particles-js" class="main-form-box">
    <div class="md-form">
        <div class="container">
            <div class="row">
                <div class="col-md-6 offset-md-3">
                    <div class="panel panel-login">
                        <div class="logo-top">
                            <a href="#"><img src="{% static 'img/enroll/logo.png' %}" alt=""/></a>
                        </div>
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-lg-12">
                                    <form id="login-form" action="{% url 'login:login_view' %}" method="post"
                                          role="form" style="display: block;">
                                        {% csrf_token %}
                                        <div class="form-group">
                                            <label class="icon-lp" style="margin: 6px 0 0 7px">
                                                <i class="layui-icon layui-icon-username"></i>
                                            </label>
                                            <input type="text" name="username" id="username" tabindex="1"
                                                   class="form-control" placeholder="用户名" value="" required=""
                                                   autoComplete="off">
                                            <span style="color: red">{{ form.username.errors.0 }}</span>
                                        </div>


                                        <div class="form-group">
                                            <label class="icon-lp" style="margin: 6px 0 0 7px">
                                                <i class="layui-icon layui-icon-password"></i>
                                            </label>
                                            <input type="password" name="password" id="Password" tabindex="2"
                                                   class="form-control" placeholder="密码" required="">
                                            <span style="color: red">{{ form.password.errors.0 }}</span>
                                        </div>

                                        <div class="form-group">
                                            <div class="row">
                                                <div class="col-sm-7">
                                                    <label class="icon-lp" style="margin: 6px 0 0 7px">
                                                        <i class="layui-icon layui-icon-vercode"
                                                           style="margin: 6px 0 0 7px"></i>
                                                    </label>
                                                    <input type="text" name="Captcha" id="Captcha" tabindex="2"
                                                           class="form-control" placeholder="请输入验证码">
                                                    <span style="color: red">{{ error_message }}</span>
                                                </div>
                                                <div class="col-sm-5">
                                                    <div style="margin: 10px 0 0 30px;">
                                                        <img src="/login/code/" alt="" id="captchaImg">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <div class="row">
                                                <div class="col-sm-6">
                                                    <input type="submit" name="login-submit" id="login-submit"
                                                           tabindex="4" class="form-control btn btn-login" value="登录">
                                                </div>

                                                <div class="col-sm-6">
                                                    <a class="form-control btn btn-login"
                                                       style="height: 100%; color: white"
                                                       href="{% url "login:enroll" %}">注册</a>
                                                </div>
                                            </div>
                                        </div>
                                    </form>

                                    <a href="{% url 'login:retrieve_view' %}" style="float: right; color: red">忘记密码?</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<script src="{% static 'js/enroll/jquery.min.js' %}"></script>
<script src="{% static 'js/enroll/bootstrap.min.js' %}"></script>
<script src="{% static 'js/enroll/particles.min.js' %}"></script>
<script src="{% static 'js/enroll/index.js' %}"></script>
<script type="text/javascript">
    $(function () {
        $('#login-form-link').click(function (e) {
            $("#login-form").delay(100).fadeIn(100);
            $("#register-form").fadeOut(100);
            $('#register-form-link').removeClass('active');
            $(this).addClass('active');
            e.preventDefault();
        });
        $('#register-form-link').click(function (e) {
            $("#register-form").delay(100).fadeIn(100);
            $("#login-form").fadeOut(100);
            $('#login-form-link').removeClass('active');
            $(this).addClass('active');
            e.preventDefault();
        });
    });

    $('.form-group input').focus(function () {
        $(this).parent().addClass('addcolor');
    }).blur(function () {
        $(this).parent().removeClass('addcolor');
    });


    document.getElementById('captchaImg').addEventListener('click', function () {
        //  调用后端视图函数以获取新的captcha图像
        fetch('/login/code/')
            .then(response => response.blob())
            .then(blob => {
                //  更新图像的src属性以显示新的captcha
                document.getElementById('captchaImg').src = URL.createObjectURL(blob);
            });
    });
</script>

</body>
</html>

templates/search.html
{% extends 'base.html' %}
{% block body %}
    <table class="layui-table" style="color: white;">
        <colgroup>
            <col width="150">
            <col width="150">
            <col>
        </colgroup>
        <thead style="background: #0078d7">
        <tr>
            <th style="text-align: center">姓名</th>
            <th style="text-align: center">年龄</th>
            <th style="text-align: center">电话</th>
            <th style="text-align: center">性别</th>
            <th style="text-align: center">值班时间</th>
        </tr>
        </thead>
        <tbody style="background: #173e5d">
        {% for worker in workers %}
            <tr>
                <td style="text-align: center">{{ worker.name }}</td>
                <td style="text-align: center">{{ worker.age }}</td>
                <td style="text-align: center">{{ worker.tel }}</td>
                <td style="text-align: center">{{ worker.get_gender_display }}</td>
                <td style="text-align: center;"><a href="/user/1/{{ worker.id }}/" style="color: white">查看</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}